# Generated by Django 4.2.1 on 2023-06-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadministration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='raisedfund',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
