# Generated by Django 4.2.1 on 2023-06-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadministration', '0002_campaign_date_campaign_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='campaign',
            new_name='campaigntable',
        ),
    ]
