# Generated by Django 4.2.1 on 2023-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadministration', '0003_rename_campaign_campaigntable'),
    ]

    operations = [
        migrations.CreateModel(
            name='crquesttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cause', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('story', models.CharField(max_length=500)),
                ('date', models.DateField(default=None)),
            ],
        ),
    ]
