# Generated by Django 4.2.1 on 2023-06-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadministration', '0004_crquesttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crquesttable',
        ),
    ]
