# Generated by Django 4.2.1 on 2023-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crquesttable',
            name='amount',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
