# Generated by Django 4.2.1 on 2023-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_donation_donationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtable',
            name='campaigntitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
